### ISSUE TITLE
docker err

### ISSUE THREAD

**Issue by sharin-sushi** [sharin-sushi/0016go_next_relation#64]
Dockerにてdoccker-compose upを実行した際、next.jsのdockerfileにてnpm run buildがエラーとなった。

**現状分かっていること**
・docker-compose時のログは下記。
・dockerを使わずにnpm run dev, npm run buid, npm run startした際にはそのエラーは発生しない。ブラウザ上で動作確認できる。そのログは[次のコメント](https://github.com/sharin-sushi/0016go_next_relation/issues/64#issuecomment-1809547304)で掲載。
ーーーー
t0016Next> docker-compose up
```
[+] Building 18.0s (10/10) FINISHED
 => [app internal] load .dockerignore      0.0s 
 => => transferring context: 2B               0.0s 
 => [app internal] load build definition from Dockerfile  0.0s
 => => transferring dockerfile: 1.71kB    0.0s 
 => [app internal] load metadata for
docker.io/library/node:14                        1.6s 
 => [app 1/6] FROM docker.io/library/node:14@sha256:a158d3b9b4e3fa813fa6c8c590b8f0a860e015ad4e59  0.0s 
 => [app internal] load build context      8.9s 
 => => transferring context: 36.34MB    8.8s 
 => CACHED [app 2/6] WORKDIR /app/src    0.0s 
 => CACHED [app 3/6] COPY /myapp/package*.json ./   0.0s 
 => CACHED [app 4/6] RUN npm install    0.0s 
 => [app 5/6] COPY . .                    6.7s 
 => ERROR [app 6/6] RUN npm run build     0.6s 
------
 > [app 6/6] RUN npm run build:
0.517
0.517 > 0016api@0.1.0 build /app/src
0.517 > next build
0.517
0.577 /app/src/node_modules/next/dist/bin/next:57
0.577 performance.mark("next-start");
0.577 ^
0.577
0.577 ReferenceError: performance is not defined
0.577     at Object.<anonymous> (/app/src/node_modules/next/dist/bin/next:57:1)
0.577     at Module._compile (internal/modules/cjs/loader.js:1114:14)
0.577     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
0.577     at Module.load (internal/modules/cjs/loader.js:979:32)
0.577     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
0.577     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
0.577     at internal/main/run_main_module.js:17:47
0.585 npm ERR! code ELIFECYCLE
0.585 npm ERR! errno 1
0.595 npm ERR! 0016api@0.1.0 build: `next build`
0.595 npm ERR! Exit status 1
0.595 npm ERR!
0.595 npm ERR! Failed at the 0016api@0.1.0 build script.
0.595 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
0.603
0.603 npm ERR! A complete log of this run can be found in:
0.603 npm ERR!     /root/.npm/_logs/2023-11-14T03_03_46_620Z-debug.log
------
failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
```

**他、ネット検索で分かったこと**

〇next.jsにはNODE_ENV値が自動で設定される仕組みがある
・npm run build, start：pruduction
・npm run dev：development
・test?：test
[Ensure Next.js is correctly respecting NODE_ENV](https://github.com/vercel/next.js/issues/19046)

〇[GitHub, next.js/vercel, issue](https://github.com/vercel/next.js/issues)で検索したが、改善策が見つからず。

**環境**
・Next.js v13.4.19
```npm list next --depth=0
t0016Next\myapp
├── react-dom@18.2.0
├── react@18.2.0
├── typescript@5.1.6
├── next@13.4.19
└その他多数
```
```
t0016Next\myapp> npm list -g  --depth=0      
略\AppData\Roaming\npm
└── (empty)
```
・Docker Engine v24.0.2
・windows 10 home, 64bit、VSCode

**Comment by sharin-sushi** [comment]
myapp> npm run dev
```
> 0016api@0.1.0 dev
> next dev -p 80   

- info Loaded env from C:\Users\略\0016go_next_relation\t0016Next\myapp\.env.development
- info Loaded env from C:\Users\略\0016go_next_relation\t0016Next\myapp\.env
- ready started server on [::]:80, url: http://localhost:80
- event compiled client and server successfully in 238 ms (18 modules)
- wait compiling...
- event compiled client and server successfully in 220 ms (18 modules)
- info Loaded env from C:\Users\略\0016go_next_relation\t0016Next\myapp\.env.development
- info Loaded env from C:\Users\略\0016go_next_relation\t0016Next\myapp\.env
- info Loaded env from C:\Users\略\0016go_next_relation\t0016Next\myapp\.env.development
- info Loaded env from C:\Users\略\0016go_next_relation\t0016Next\myapp\.env
- wait compiling /_error (client and server)...
- event compiled client and server successfully in 559 ms (174 modules)
- warn Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
- wait compiling / (client and server)...
- event compiled client and server successfully in 343 ms (245 modules)
- warn Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
domain.backendHost: http://localhost:8080
```
\myapp> npm run build
```
> 0016api@0.1.0 build
> next build

- warn You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies 
in the project and is strongly advised against. Read more: https://nextjs.org/docs/messages/non-standard-node-env
- info Loaded env from C:\Users\略\0016go_next_relation\t0016Next\myapp\.env.production
- info Loaded env from C:\Users\略\0016go_next_relation\t0016Next\myapp\.env
- info Linting and checking validity of types  
- info Creating an optimized production build
- info Compiled successfully
- info Collecting page data  
- info Generating static pages (4/4)
- info Finalizing page optimization

Route (pages)                              Size     First Load JS
┌ λ /                                      3.02 kB        87.9 kB
├ ○ /404                                   182 B            76 kB
├ λ /create                                3.08 kB         144 kB
├ λ /delete                                2.71 kB         136 kB
├ λ /edit                                  3.26 kB         144 kB
├ λ /karaokelist/sings                     1.35 kB        86.2 kB
├ λ /mypage                                1.36 kB        79.6 kB
├ ○ /signin                                1.31 kB          87 kB
└ ○ /signup                                1.41 kB        87.1 kB
+ First Load JS shared by all              75.8 kB
  ├ chunks/framework-63157d71ad419e09.js   45.2 kB
  ├ chunks/main-c6c319de9f7d0316.js        29.4 kB
  ├ chunks/pages/_app-aea6920bd27938ca.js  195 B
  └ chunks/webpack-87b3a303122f2f0d.js     995 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
![image](https://github.com/sharin-sushi/0016go_next_relation/assets/127638412/f4653637-fe00-40b7-af87-87b86b82cf38)
```

\myapp> npm start
```
>0016api@0.1.0 start
>next start -p 80

- warn You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies 
in the project and is strongly advised against. Read more: https://nextjs.org/docs/messages/non-standard-node-env
- ready started server on [::]:80, url: http://localhost:80
- info Loaded env from C:\Users\略\0016go_next_relation\t0016Next\myapp\.env.production
- info Loaded env from C:\Users\略\0016go_next_relation\t0016Next\myapp\.env
- info Loaded env from C:\Users略\0016go_next_relation\t0016Next\myapp\.env.production
- info Loaded env from C:\Users\略\0016go_next_relation\t0016Next\myapp\.env

```

**Comment by sharin-sushi** [comment]
**経過**
悪化した。
ーーーー
・react, react-dom, nextを一度アンインストール
・react, react-domをインストール
・next 13.4.19をインストール
・npm run build
```> 0016api@0.1.0 build
> next build

 ⚠ You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies in the project and is strongly advised against. Read more: https://nextjs.org/docs/messages/non-standard-node-env
 ✓ Linting and checking validity of types    
 ✓ Creating an optimized production build
 ✓ Compiled successfully
 ✓ Collecting page data  
Generating static pages (0/4)  [    ]Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted
(略)
 ✓ Generating static pages (4/4)```
案の定
```myapp> npm start

> 0016api@0.1.0 start
> next start -p 80   

 ⚠ You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies in the project and is strongly advised against. Read more: https://nextjs.org/docs/messages/non-standard-node-env
[Error: ENOENT: no such file or directory, open 'C:\\略\\0016go_next_relation\t0016Next\myapp\.next\prerender-manifest.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\略\\0016go_next_relation\\t0016Next\\myapp\\.next\\prerender-manifest.json'
}```

**Comment by sharin-sushi** [comment]
このリポジトリ内の何かが悪いのか確認するため、[別リポジトリ0015](https://github.com/sharin-sushi/0015docker/issues/1)で確認作業を実施しました。

結果、同様の症状が見られました。
これより、node.jsや環境設定等の、コード外が原因になっている可能性が高いです。
