### ISSUE TITLE
docker上で.envを読み込めない(godotenv)

### ISSUE THREAD

**Issue by sharin-sushi** [sharin-sushi/0016go_next_relation#68]
①docker外なら.envを読み込めるが、②docker上では.envを読み込めない。
(godotenv)
ーーーーーーーーー
①docker外
(環境変数含めた外部秘の値は伏せた)
```
cmd> go run .
got .env file is go_env 　←fmt.Printf
path=(user):(pass)@tcp(db:3306)/(db)?charset=utf8&parseTime=true ←fmt.Prinf
2023/11/16 22:41:51 C:/略/0016go_next_relation/t0016Go/internal/utility/auth.go:64
[error] failed to initialize database, got error dial tcp: lookup _db: no such host
panic: failed to connect database

goroutine 1 [running]:
github.com/sharin-sushi/0016go_next_relation/internal/utility.InitDb()
       C:/略/0016go_next_relation/t0016Go/internal/utility/auth.go:67 +0x3f7
main.start()
       C:/略/0016go_next_relation/t0016Go/cmd/main.go:21 +0x2e
main.main()
       C:/略/0016go_next_relation/t0016Go/cmd/main.go:17 +0x17
exit status 2
```

②docker上
a) db接続に必要であるが、環境変数を取得できない。
(毎回`docuker-compose build`してから`docker-compose up`してる)
```
0016go_next_relation-api-1  | 2023/11/16 13:22:32 Error loading go/.env file!!
0016go_next_relation-api-1  | exit status 1
0016go_next_relation-api-1 exited with code 1
```
b) db接続関連のコードをコメントアウト化したところ、localhost:8080からgoapiへ取得できることは確認できた。]
```
0016go_next_relation-api-1  | [GIN] 2023/11/16 - 14:58:29 | 500 |     11.0214ms |      172.18.0.1 | GET      "/"
```
また、② a) のbuild, up時のログいは以下の通り。
```
docker-compose build
[+] Building 3.5s (19/19) FINISHED
 => [db internal] load .dockerignore                                                                                            0.0s 
 => => transferring context: 2B                                                                                                 0.0s 
 => [db internal] load build definition from Dockerfile                                                                         0.0s 
 => => transferring dockerfile: 263B                                                                                            0.0s 
 => [db internal] load metadata for docker.io/library/mysql:latest                                                              0.0s 
 => [db internal] load build context                                                                                            0.0s 
 => => transferring context: 28B                                                                                                0.0s 
 => [db 1/2] FROM docker.io/library/mysql                                                                                       0.0s 
 => CACHED [db 2/2] ADD ./my.cnf /etc/mysql/conf.d/my.cnf                                                                       0.0s 
 => [db] exporting to image                                                                                                     0.0s 
 => => writing image sha256:788a56a98de4f02112c2739527e1c6c032385639121b9a99c9567db4f33b42df                                    0.0s 
 => => naming to docker.io/library/mysql                                                                                        0.0s 
 => [api internal] load .dockerignore                                                                                           0.0s 
 => => transferring context: 2B                                                                                                 0.0s 
 => [api internal] load build definition from Dockerfile                                                                        0.0s 
 => => transferring dockerfile: 2.23kB                                                                                          0.0s 
 => [api] resolve image config for docker.io/docker/dockerfile:1                                                                1.7s 
 => CACHED [api] docker-image://docker.io/docker/dockerfile:1@sha256:ac85f380a63b13dfcefa89046420e1781752bab202122f8f50032edf3  0.0s 
 => [api internal] load metadata for docker.io/library/golang:1.19                                                              0.9s 
 => [api 1/5] FROM docker.io/library/golang:1.19@sha256:3025bf670b8363ec9f1b4c4f27348e6d9b7fec607c47e401e40df816853e743a        0.0s 
 => [api internal] load build context                                                                                           0.0s 
 => => transferring context: 60.72kB                                                                                            0.0s 
 => CACHED [api 2/5] WORKDIR /api/src                                                                                           0.0s 
 => CACHED [api 3/5] COPY go.mod go.sum ./                                                                                      0.0s 
 => CACHED [api 4/5] RUN go mod download                                                                                        0.0s 
 => [api 5/5] COPY * ./                                                                                                         0.0s 
 => [api] exporting to image                                                                                                    0.1s 
 => => exporting layers                                                                                                         0.0s 
 => => writing image sha256:59f275af7d7d092898721a9206150f92ac6308ae8b6dbe76cf91c7839c1ecd1e                                    0.0s 
 => => naming to docker.io/library/0016go_next_relation-api                                                                     0.0s 
PS C:\(略)\0016go_next_relation> docker-compose up   
[+] Running 2/2
 ✔ Container test_db                     Recreated                                                                              0.5s 
 ✔ Container 0016go_next_relation-api-1  Recreated                                                                              0.8s 
Attaching to 0016go_next_relation-api-1, test_db
test_db                     | 2023-11-16 12:50:19+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.2.0-1.el8 started.
test_db                     | 2023-11-16 12:50:19+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
test_db                     | 2023-11-16 12:50:19+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.2.0-1.el8 started.
test_db                     | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
test_db                     | 2023-11-16T12:50:19.512840Z 0 [System] [MY-015015] [Server] MySQL Server - start.
test_db                     | 2023-11-16T12:50:19.728853Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
test_db                     | 2023-11-16T12:50:19.728878Z 0 [Warning] [MY-011069] [Server] The syntax '--character-set-client-handshake' is deprecated and will be removed in a future release.
test_db                     | 2023-11-16T12:50:19.730840Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.2.0) starting as process 1
test_db                     | 2023-11-16T12:50:19.732381Z 0 [Warning] [MY-013242] [Server] --character-set-server: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
test_db                     | 2023-11-16T12:50:19.732396Z 0 [Warning] [MY-013244] [Server] --collation-server: 'utf8mb3_unicode_ci' is a collation of the deprecated character set UTF8MB3. Please consider using UTF8MB4 with an appropriate collation instead.
test_db                     | 2023-11-16T12:50:19.737784Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
test_db                     | 2023-11-16T12:50:20.464459Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.     
test_db                     | 2023-11-16T12:50:20.464552Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
test_db                     | 2023-11-16T12:50:20.469838Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
test_db                     | 2023-11-16T12:50:20.524960Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
test_db                     | 2023-11-16T12:50:20.525084Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.2.0'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
0016go_next_relation-api-1  | 2023/11/16 12:50:28 Error loading .env file!!
0016go_next_relation-api-1  | exit status 1
0016go_next_relation-api-1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...
[+] Stopping 1/0
[+] Killing 1/126go_next_relation-api-1  Stopped                                                                                0.0s 
 ✔ Container 0016go_next_relation-api-1  Stopped                                                                                0.0s 
 ✔ Container test_db                     Stopped                                                                                0.5s 
 ✔ Container test_db  Killed                                                                                                    0.4s 
canceled
```
ーーーーー
以上により、原因はdocker上でgodotenvが起動していない(インストールできていない？)ことを予想している。

**Comment by sharin-sushi** [comment]
`go install github.com/joho/godotenv/cmd/godotenv@latest`
してみたが結果変わらず。

**Comment by sharin-sushi** [comment]
docker外では使用できたが、docker上では使用できなかった。
そのため、開発向けにgodotenv、docker上向けにはdockercomposeでgoの環境変数を取得するようにした。
https://github.com/sharin-sushi/0016go_next_relation/pull/69#issue-1997360521
